fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';
fred = 'fredfredfredfred';fred = 'fredfredfredfred';fred = 'fredfredfredfred';

console.log('fred length coffee saf', fred.length);